name: Linux VPS Setup

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y   openssh-server
    
    - name: Enable SSH Server
      run: sudo systemctl start ssh && sudo systemctl enable ssh

    - name: Set Default Password (Auto)
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Allow SSH Login
      run: sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && sudo systemctl restart ssh

    - name: Create SSH 
      run: ssh -o StrictHostKeyChecking=no -R sophiekid:22:localhost:22 serveo.net
